version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.2
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Docker daemon socket (optional)
