name: Dependency Insight

on: push

defaults:
  run:
    working-directory: ./

jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Run dependency analysis
        uses: mridang/action-dependency-insight@v1
